return {
  {
    "mason-org/mason.nvim",
    lazy = false,
    opts = {
      PATH = "prepend",
    },
    cmd = {
      "Mason",
      "MasonInstall",
      "MasonUninstall",
      "MasonUninstallAll",
      "MasonLog",
      "MasonUpdate",
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "mason-org/mason.nvim" },
    cmd = {
      "MasonToolsInstall",
      "MasonToolsInstallSync",
      "MasonToolsUpdate",
      "MasonToolsUpdateSync",
      "MasonToolsClean",
    },
    opts = {
      ensure_installed = {
        "lua-language-server",
        "gopls",
        "pyright",
        "bash-language-server",
        "yaml-language-server",
        "ansible-language-server",
        "efm",
        "starpls",
        "marksman",
        "stylua",
        "shfmt",
        "shellcheck",
        "black",
        "isort",
        "prettier",
        "prettierd",
      },
      auto_update = false,
      run_on_start = false,
    },
  },
}
